name: Publish Demo Apks
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'requestly-android-sdk version'
        required: true 
        type: string

jobs:
  create:
    name: Create Apks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # CryptoDemo
      - name: Build CryptoDemo APK
        working-directory: ./CryptoDemo
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Renaming Apk
        working-directory: ./CryptoDemo
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/cryptodemo-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: demo-apks
          path: ./CryptoDemo/app/build/outputs/apk/debug/cryptodemo-debug.apk
      # Pokedex
      - name: Build Pokedex APK
        working-directory: ./Pokedex
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Renaming Apk
        working-directory: ./Pokedex
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/pokedex-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: demo-apks
          path: ./Pokedex/app/build/outputs/apk/debug/pokedex-debug.apk

  release:
    name: Release APKS
    needs: create
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: demo-apks
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ inputs.version }}
          files: |
            demo-apks/cryptodemo-debug.apk
            demo-apks/pokedex-debug.apk
